version: 2.1

jobs:
  build_test_sonar:
    docker:
      - image: ghcr.io/wy-bbw/mm_solver_builder
        auth:
          username: wy-bbw
          password: $GITHUB_REGISTRY_PASSWORD
    steps:
      - checkout
      - run:
          name: sonarcloud needs some extra love - this is not copy paste it is not
          command: |
            mkdir build
            cd build
            wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
      - run:
          name: build mmsolver
          command: |
            cd build
            conan profile detect
            cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
            ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir /tmp cmake --build .
      - run:
          name: run tests
          command: |
            cd build
            ctest . --output-on-failure
            gcovr -r .. --sonarqube coverage.xml --exclude-directories ../test
      - sonarcloud/scan
  asan_build_test:
    docker:
      - image: ghcr.io/wy-bbw/mm_solver_builder
        auth:
          username: wy-bbw
          password: $GITHUB_REGISTRY_PASSWORD
    steps:
      - checkout
      - run:
          name: build mmsolver with asan
          command: |
            mkdir build
            cd build
            conan profile detect
            cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -G Ninja -DCMAKE_BUILD_TYPE=Debug -DUSE_ASAN=ON
            cmake --build .
      - run:
          name: run tests with asan
          command: |
            cd build
            ctest . --output-on-failure
  ubsan_build_test:
    docker:
      - image: ghcr.io/wy-bbw/mm_solver_builder
        auth:
          username: wy-bbw
          password: $GITHUB_REGISTRY_PASSWORD
    steps:
      - checkout
      - run:
          name: build mmsolver with ubsan
          command: |
            mkdir build
            cd build
            conan profile detect
            cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -G Ninja -DCMAKE_BUILD_TYPE=Debug -DUSE_UBSAN=ON
            cmake --build .
      - run:
          name: run tests with ubsan
          command: |
            cd build
            ctest . --output-on-failure

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1
workflows:
  main:
    jobs:
      - build_test_sonar:
          context: sonarcloud
          filters:
            branches:
              only:
                - develop
                - master
      - asan_build_test:
          filters:
            branches:
              only:
                - develop
                - master
      - ubsan_build_test:
          filters:
            branches:
              only:
                - develop
                - master